### ISSUE TITLE
Today morning can't open in 2 sites itella module

### ISSUE THREAD

**Issue by kristogaleta** [ItellaPlugins/itella-shipping-prestashop#41] opened 2024-09-11 07:26 UTC
Today morning no changes are made getting this error

![image](https://github.com/user-attachments/assets/fe564dca-8519-4806-bb89-30b33f8d3689)

Any idea what is causing that?

**Comment by kristogaleta** [comment] 2024-09-11 07:27
And user side also cant open pickup points...

**Comment by kristogaleta** [comment] 2024-09-11 07:58
Prestashop version 8.1.5
Module version: Smartpost Shipping v1.2.13 - by Mijora.lt

All shops from our side are affected and users can't choose pickup points..

But we have one shop running 1.7.6 and this one works with no problems..

**Comment by wwatu1337** [comment] 2024-09-11 09:40
Same issue on 8.1.7

**Comment by rktvsiim** [comment] 2024-09-11 12:33
Same issue with: 

- Prestashop **8.1.7** 
- PHP **8.1.29**
- Smartpost Shipping **v1.2.13**

![image](https://github.com/user-attachments/assets/42bf2404-1d9d-4cee-a1f8-4c5508be6668)
![image](https://github.com/user-attachments/assets/2fbf6fb9-a836-42a0-b3e1-97a2ebd651de)
![image](https://github.com/user-attachments/assets/53bc9c01-5ea7-4e91-8346-8b363a9acba6)
![image](https://github.com/user-attachments/assets/c6928484-6e45-402e-ba3d-96e00b798514)

**Comment by markakk** [comment] 2024-09-12 06:29
Hello,

Yesterday, for the first half of the day, there was a problem with getting the list of pickup points from the Itella server. The problem is currently fixed. We can see that when such a problem occurs, in the module errors are received. Itella will decide if such errors in the module will be fixed.

**Closed by markakk** 2024-09-12 06:29 UTC

**Comment by marleonee** [comment] 2024-10-01 12:11
I have the same problem now!
